apiVersion: v1
kind: Service
metadata:
  name: project2-service
spec:
  type: NodePort
  selector:
    app: project2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
